version: "3.7"

services:
  postgresql:
    image: "postgresql"
    container_name: "postgresql"
    restart: "always"
    expose:
      - "5432"
    volumes: "./postgresql/data:/var/lib/postgresql/data"
    env_file: "./postgresql/.env"
