version: "3.7"

services:
  postgresql:
    image: "postgresql"
    container_name: "postgresql"
    restart: "always"
    expose:
      - "5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    env_file: "./postgresql/.env"

  backend:
    build: "./backend/"
    container_name: "django"
    restart: "always"
    expose:
      - "8000"
    env_file: "./backend/.env"
    volumes:
      - "./backend:/school/"
      - "static_volume:/school/static"
      - "media_volume:/school/media"
    depends_on:
      - "postgresql"

  nginx:
    build: "./nginx"
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./nignx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "static_volume:/school/static"
      - "media_volume:/school/media"
    depends_on:
      - "backend"
      - "postgresql"
